# Generated by Django 5.2.17 on 2026-09-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_name", models.CharField(max_length=100)),
                ("status", models.CharField(default="success", max_length=50)),
                ("summary", models.CharField(max_length=255)),
                ("items_processed", models.IntegerField(default=0)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "automation_task_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IdentityCandidateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_user_key", models.CharField(db_index=True, max_length=255)),
                ("sfp_name", models.CharField(db_index=True, max_length=255)),
                (
                    "candidate_global_user_key",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "link_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("review_candidate", "Review Candidate (70%-89%)"),
                            (
                                "high_confidence_candidate",
                                "High Confidence Candidate (90%+)",
                            ),
                            ("confirmed", "Confirmed Link"),
                            ("rejected", "Rejected Link"),
                        ],
                        default="candidate",
                        max_length=50,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "identity_candidate_links",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MediaCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_target_title", models.CharField(db_index=True, max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("film", "Film Poster"),
                            ("tv", "TV Series Art"),
                            ("game", "Video Game Cover"),
                            ("album", "Music Album Cover"),
                            ("book", "Book Cover"),
                            ("thumbnail", "Thumbnail / Supporting Media"),
                        ],
                        default="film",
                        max_length=50,
                    ),
                ),
                ("candidate_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("source_url", models.URLField(max_length=1000)),
                ("source_domain", models.CharField(max_length=255)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("aspect_ratio", models.CharField(default="1:1", max_length=50)),
                ("quality_score", models.FloatField(default=0.0)),
                (
                    "rights_status",
                    models.CharField(default="editorial_caution", max_length=50),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Validation"),
                            ("approved", "Approved"),
                            ("review_required", "Review Required"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "media_candidates",
                "ordering": ["-quality_score", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ModuleAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_key", models.CharField(db_index=True, max_length=255)),
                ("sfp_name", models.CharField(db_index=True, max_length=255)),
                ("usage_count", models.IntegerField(default=0)),
                ("approval_count", models.IntegerField(default=0)),
                ("rejection_count", models.IntegerField(default=0)),
                ("escalation_count", models.IntegerField(default=0)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "module_analytics_snapshots",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_key", models.CharField(max_length=255, unique=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("transcript", "Transcript"),
                            ("review", "Review"),
                            ("handbook", "Handbook"),
                            ("precedent", "Precedent"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("sfp_name", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "vector_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Embedding"),
                            ("embedded", "Embedded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_json",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "retrieval_documents",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MediaProvenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=1000)),
                ("source_domain", models.CharField(max_length=255)),
                (
                    "provenance_status",
                    models.CharField(default="verified", max_length=50),
                ),
                ("review_required", models.BooleanField(default=False)),
                ("assistance_applied", models.BooleanField(default=True)),
                ("autonomous_origin", models.BooleanField(default=False)),
                (
                    "agent_package_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance_logs",
                        to="learnami.mediacandidate",
                    ),
                ),
            ],
            options={
                "db_table": "media_provenance_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPostDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content_type", models.CharField(default="film", max_length=50)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Mode"),
                            ("assisted", "Assisted Mode"),
                            ("autonomous", "Autonomous Mode"),
                        ],
                        default="assisted",
                        max_length=50,
                    ),
                ),
                ("content_body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("packaged", "Packaged for WordPress"),
                            ("synced", "Synced to WordPress"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("wordpress_post_id", models.IntegerField(blank=True, null=True)),
                ("package_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learnami.mediacandidate",
                    ),
                ),
            ],
            options={
                "db_table": "review_post_drafts",
                "ordering": ["-id"],
            },
        ),
    ]
