# Generated by Django 5.2.17 on 2026-09-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learnami", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wp_user_id", models.IntegerField(db_index=True)),
                ("author_username", models.CharField(max_length=150)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("review", "Review Post"),
                            ("forum_topic", "Forum Topic"),
                            ("comment", "Comment / Reply"),
                            ("poll", "Poll Submission"),
                        ],
                        default="review",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Moderation"),
                            ("approved", "Approved / Published"),
                            ("flagged", "Flagged"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("assistance_applied", models.BooleanField(default=False)),
                ("assistance_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_submissions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System Automation"),
                            ("admin", "Admin / Chief of Staff"),
                            ("agent", "Autonomous Agent"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=150, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "governance_audit_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserOnboardingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wp_user_id", models.IntegerField(db_index=True, unique=True)),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("avatar_completed", models.BooleanField(default=False)),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("flagged", "Flagged for Review"),
                            ("rejected", "Rejected / High Risk"),
                        ],
                        default="approved",
                        max_length=30,
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                ("risk_reasons", models.TextField(blank=True, null=True)),
                (
                    "onboarding_stage",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("email_pending", "Email Pending"),
                            ("progressive_asks", "Progressive Asks Incomplete"),
                            ("completed", "Onboarding Complete"),
                            ("escalated", "Escalated to Admin"),
                        ],
                        default="registered",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(default="subscriber_probationary", max_length=50),
                ),
                ("can_post", models.BooleanField(default=False)),
                ("can_comment", models.BooleanField(default=False)),
                ("can_vote", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_onboarding_states",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ModerationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wp_user_id", models.IntegerField()),
                ("reason_code", models.CharField(max_length=100)),
                ("flagged_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open / Pending"),
                            ("resolved_approved", "Resolved - Approved"),
                            ("resolved_rejected", "Resolved - Rejected"),
                            ("escalated", "Escalated to Senior Moderator"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("moderator_notes", models.TextField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_cases",
                        to="learnami.contentsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "moderation_cases",
                "ordering": ["-id"],
            },
        ),
    ]
