# Generated by Django 5.2.17 on 2026-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learnami", "0002_contentsubmission_governanceauditlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_user_key", models.CharField(db_index=True, max_length=255)),
                ("consent_type", models.CharField(max_length=150)),
                ("granted", models.BooleanField(default=True)),
                ("source_sfp", models.CharField(blank=True, max_length=150, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "consent_records",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrchestrationEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=150)),
                (
                    "source_actor",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "target_layer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="dispatched", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "orchestration_event_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrchestrationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_key", models.CharField(max_length=150, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=150)),
                (
                    "source_layer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_layer", models.CharField(max_length=100)),
                (
                    "target_actor",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "orchestration_rules",
                "ordering": ["priority", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_key", models.CharField(max_length=150)),
                ("requested_by", models.CharField(max_length=150)),
                ("proposed_config", models.JSONField(blank=True, default=dict)),
                ("justification", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "policy_change_requests",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_key", models.CharField(max_length=150, unique=True)),
                ("policy_type", models.CharField(max_length=100)),
                (
                    "platform_context",
                    models.CharField(default="global", max_length=100),
                ),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rule_config", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.CharField(default="v1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "policy_rules",
                "ordering": ["priority", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicySimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simulation_name", models.CharField(max_length=200)),
                ("policy_key", models.CharField(max_length=150)),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("proposed_config", models.JSONField(blank=True, default=dict)),
                ("sample_context", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("passed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "policy_simulation_results",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_role", models.CharField(max_length=150)),
                ("data_class", models.CharField(max_length=150)),
                ("target_key", models.CharField(blank=True, max_length=255, null=True)),
                ("decision", models.CharField(default="allowed", max_length=50)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "privacy_access_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseReadinessCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_type", models.CharField(max_length=100)),
                ("scope_key", models.CharField(max_length=150)),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("status", models.CharField(default="passed", max_length=50)),
                ("score", models.FloatField(default=100.0)),
                ("checks_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "release_readiness_checks",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReplayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replay_name", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=150)),
                (
                    "source_layer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="completed", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "replay_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_type", models.CharField(max_length=100)),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("status", models.CharField(default="completed", max_length=50)),
                ("findings_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "review_cycles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RunbookExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runbook_key", models.CharField(max_length=150)),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("status", models.CharField(default="running", max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                ("steps_completed", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "runbook_executions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SFPRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sfp_key", models.CharField(max_length=100, unique=True)),
                ("sfp_name", models.CharField(max_length=200)),
                ("capabilities_json", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sfp_registries",
                "ordering": ["sfp_key"],
            },
        ),
        migrations.CreateModel(
            name="SystemBlueprintSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_name", models.CharField(max_length=200)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_blueprint_snapshots",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SystemConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conflict_type", models.CharField(max_length=150)),
                ("severity", models.CharField(default="medium", max_length=50)),
                ("description", models.TextField()),
                ("status", models.CharField(default="open", max_length=50)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_conflicts",
                "ordering": ["-id"],
            },
        ),
    ]
