"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ii4!z8d%)ie)un4e-_js6o))f6ubt@1+%he5!&2ud+58$#c3n!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Allow Railway-injected domain + localhost
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "learnami",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "learnami.context_processors.db_status_processor",

            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database Configuration - Priority: env vars > db_config.json > SQLite fallback
import json
import pymysql
import django.db.backends.base.base

# Bypass MySQL 8 version check for cPanel MySQL 5.7
django.db.backends.base.base.BaseDatabaseWrapper.check_database_version_supported = lambda self: None
pymysql.install_as_MySQLdb()

# Railway / production: set DB_ env vars in the Railway Variables dashboard
_db_host = os.environ.get("DB_HOST", "")
_db_name = os.environ.get("DB_NAME", "")
_db_user = os.environ.get("DB_USER", "")
_db_password = os.environ.get("DB_PASSWORD", "")
_db_port = os.environ.get("DB_PORT", "3306")

if _db_host and _db_name:
    # Use env-var-supplied MySQL credentials (Railway production)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": _db_name,
            "USER": _db_user,
            "PASSWORD": _db_password,
            "HOST": _db_host,
            "PORT": _db_port,
            "OPTIONS": {
                "charset": "utf8mb4",
                "connect_timeout": 6,
            },
        }
    }
else:
    # Local dev: fall back to db_config.json then SQLite
    CONFIG_FILE = BASE_DIR / "db_config.json"
    db_cfg = {}
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                db_cfg = json.load(f)
        except Exception:
            db_cfg = {}

    if db_cfg.get("ENGINE") == "mysql" and db_cfg.get("HOST") and db_cfg.get("NAME"):
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": db_cfg.get("NAME"),
                "USER": db_cfg.get("USER", ""),
                "PASSWORD": db_cfg.get("PASSWORD", ""),
                "HOST": db_cfg.get("HOST", "127.0.0.1"),
                "PORT": str(db_cfg.get("PORT", "3306")),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "connect_timeout": 6,
                },
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Required for collectstatic in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
